### ISSUE TITLE
Is this product used in production?

### ISSUE THREAD

**Issue by idgserpro** [collective/collective.es.plone#1]
@jensens do you use this product in production? I found his idea interesting. We have portals where several content managers add content at the same time. This slows down the portal for authenticated users. We also need to index the content in Elastic (which makes indexing even slower). In this scenario, `collective.elastic.plone` seems to be a good solution for us. I tested it here and it seems to work. In our case, it's Plone 4.3.

**Comment by jensens** [comment]
Yes, we (spec. @agitator)  uses it in Plone 5.1+ - that's why we created this add on and https://github.com/collective/collective.elastic.ingest/  
It works fine but needs documentation and is not tested well outside our use case - which in fact covers already a lot.
Fun it works in 4.3 as well, as we never tested it there.

I would consider it stable, but not feature-complete: 
- no ExtendedPathIndex replacement possible.
- no examples/ code stubs for custom direct ES queries.
- security: no filter of ES data (not a problem when used as ElasticSearchProxyIndex)  for custom queries.
- more tests needed.
- ingest mapping is complex, default mapping may need adjustments, for customized sites a manual customized mapping is probably needed.

I would really love to see this pushed a bit, since I think its a good way to solve our bottleneck portal-catalog.
If you have any questions please
